leftnav:
- identifier: af10bb11-d564-c668-ade8-9bfc57931157
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 602a3449-62bd-5866-c320-6e738ad51e8c
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 3174a261-7ad4-b8e9-a80d-6c0b8b3b0aa5
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: b93750ce-9eb6-2e0d-2d9a-a7ba7e1919c4
  name: Assignments and Exams
  pageRef: /pages/assignments-and-exams
  weight: 40
- identifier: 2ae49847-8994-3823-c18d-6c2bf59246d2
  name: Projects
  pageRef: /pages/projects
  weight: 50
